# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: da93640c2ae29df07cbc1d36d6110b1378e93457c8b847aa2b89398708ce946fec4f7a291cb7bced4be1af4f33fe3ff98a284e23b92519f26beb65c23e083101

test:
  secret_key_base: a359aad47254fe46a59d97b03b4a52b40e5861e471083bd5f0cb3268d5b53b21b5c17fad95162f3727178b957d4a9f5207d372bec25b492c016765ac5e803deb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
